- hosts: localhost
  tasks:
  - name: login to ocp-cluster
    redhat.openshift.openshift_auth:
      host: https://api.ocp4.example.com:6443
      username: admin
      password: redhat
      validate_certs: no
    register: ocp_auth_result
  - name: deploy hello-world pod
    k8s: 
      state: present
      apply: yes
      namespace: ansible-ocp
      host: https://api.ocp4.example.com:6443
      api_key: "{{ ocp_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
           name: hello-openshift
           labels:
             app: hello-openshift
        spec:    
          selector:
            matchLabels:
              app: hello-openshift
           replicas: 1
           template:
             metadata:
                labels:
                  app: hello-openshift
              spec:
                containers:
                - name: hello-openshift
                  image: openshift/hello-openshift
                  ports:
                  - containerPort: 8080
                    protocol: TCP
                  resources:
                     requests:
                        cpu: 300m
                        memory: 64Mi
                      limits:
                         cpu: 600m
                         memory: 128Mi
      - name: create service using inline definition
        k8s:
         state: present
         apply: yes
         namespace: ansible-ocp
         host: https://api.ocp4.example.com:6443
         api_key: "{{ ocp_auth_result.k8s_auth.api_key }}"
         validate_certs: no
         definition:
           apiVersion: v1
           kind: Service
           metadata:
             name: hello-svc
             namespace: ansible-ocp
           spec:
             ports:
             - port: 8080
               protocol: TCP
               targetPort: 8080
             selector:
                app: hello-openshift
                type: ClusterIP
      - name: create a route exposing service 
        redhat.openshift,openshift_route:
          service: hello-svc
          host: https://api.ocp4.example.com:6443
          api_key: "{{ ocp_auth_result.k8s_auth.api_key }}"
          validate_certs: no
          namespace: ansible-ocp
        register: route

      - name: ensure the route is displayed
        debug:
          msg: "The application can be accessed  using the url http://{{route['result']['spec']['host']}}"
              
    
