apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: landing
   namespace: assemble
spec:
  rules:
    - host: landing.apps.ocp4.example.com
      http:
        paths:
          - path: /
            pathTypr: ImplementationSpecific
            backend:
              service:
                name: landing
                port: 
                  number: 8080
  
apiVersion: v1
kind: Service
metadata:
  name: landing
  namespace: assemble 
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
   selector:
      app: landing
   type: ClusterIP   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: assemble
 spec:
   replicas: 1
   selector:
     matchLabels: 
        app: landing
   template:
     metadata: 
        labels:
          app: landing
     spec:     
       containers:
         - image: registry.ocp4.example.com:8443/redhattraining/versioned-hello:v1.0
           name:  landing
          ports:
            - containerPort: 8080
              protocol: TCP
